name: CI
on:
  push:
    branches: ["master"]
jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v5
      - name: Build and push Docker image
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
          docker build -t ghcr.io/qpupier/computor-v2/env:latest .
          docker push ghcr.io/qpupier/computor-v2/env:latest
  compile:
    needs: build-image
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/qpupier/computor-v2/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: make -j
      - name: Save compiled binary
        uses: actions/upload-artifact@v7
        with:
          name: binary
          path: .
          retention-days: 1
  test:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: read
    container:
      image: ghcr.io/qpupier/computor-v2/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        test: [format, logic_error, numbers, complexes, matrices, polynomials, subject, bonus]
    steps:
      - name: Download artifact with retry
        uses: nick-fields/retry@v3
        with:
          timeout_minutes: 2
          max_attempts: 5
          retry_wait_seconds: 5
          uses: actions/download-artifact@v4
          with: |
            name: binary
      - run: chmod +x unit_tests/${{ matrix.test }}.sh computor-v2
      - name: Run ${{ matrix.test }}
        run: ./unit_tests/${{ matrix.test }}.sh debug
