# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    CI.yml                                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: qpupier <qpupier@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/02 20:28:20 by qpupier           #+#    #+#              #
#    Updated: 2026/03/02 20:39:03 by qpupier          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

name: CI
on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Valgrind
        run: sudo apt-get install -y valgrind
      - name: Compilation
        run: make -j
      - name: Unit tests - Format
        run: ./unit_tests/format.sh debug
      - name: Unit tests - Logic errors
        run: ./unit_tests/logic_error.sh debug
      - name: Unit tests - Numbers
        run: ./unit_tests/numbers.sh debug
