# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    CI.yml                                             :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: qpupier <qpupier@student.42lyon.fr>        +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2026/03/02 20:28:20 by qpupier           #+#    #+#              #
#    Updated: 2026/03/02 20:39:03 by qpupier          ###   ########lyon.fr    #
#                                                                              #
# **************************************************************************** #

name: CI
on:
  push:
    branches: ["master"]
jobs:
  compile:
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v5
      - name: Build
        run: make -j
      - name: Save compiled binary
        uses: actions/upload-artifact@v4
        with:
          name: binary
          path: .
          retention-days: 1
  test:
    needs: compile
    runs-on: ubuntu-latest
    permissions:
      packages: read
    container:
      image: ghcr.io/${{ github.repository }}/env:latest
      credentials:
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}
    strategy:
      fail-fast: false
      matrix:
        test: [format, logic_error, numbers, complexes, matrices, polynomials, subject, bonus]
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: binary
      - name: Run ${{ matrix.test }}
        run: ./unit_tests/${{ matrix.test }}.sh debug
